version: "3"
services:
  tma-postgres:
    image: postgres
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    network_mode: host
  label-manager:
    build: ../label-manager
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../scripts/backup:/root/backup
    depends_on:
      - tma-postgres
    network_mode: host
volumes:
  postgres_vol:
  
